ARG FEDORA_MAJOR_VERSION
FROM quay.io/fedora/fedora-bootc:${FEDORA_MAJOR_VERSION}

RUN dnf install -y \
  dnsmasq

COPY ./containers/router-bootc/router.conf /etc/dnsmasq.d/

RUN bootc container lint
