FROM quay.io/fedora/fedora-bootc:42
ARG TARGETARCH

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

COPY ./containers/lima/files/lima-guestagent-${TARGETARCH} /usr/bin/lima-guestagent
COPY ./containers/lima/files/lima-guestagent.service /etc/systemd/system/

RUN dnf install -y --best \
  podman \
  openssh-server \
  cloud-init \
  sshfs \
  dnf5-plugins && \
  dnf clean all && \
  systemctl enable sshd && \
  systemctl enable lima-guestagent && \
  ln -s /var /Users

RUN bootc container lint
