ARG FEDORA_MAJOR_VERSION
ARG BASE_REPO=ghcr.io/kevindurb
FROM ${BASE_REPO}/kde-bootc:${FEDORA_MAJOR_VERSION}

RUN dnf install -y \
  plasma-bigscreen \
  plasma-bigscreen-wayland && \
  dnf clean all

RUN bootc container lint
