---
version: 3

vars:
  FEDORA_MAJOR_VERSION: latest
  ARCH: amd64
  BOOTC_IMAGE_TYPE: raw

tasks:
  full-build:
    vars:
      TAG: 'localhost/{{.NAME}}-bootc'
    requires:
      vars: [NAME]
    cmds:
      - task: build
        vars:
          FILE: './containers/{{.NAME}}/Containerfile'
          TAG: '{{.TAG}}'
      - task: bootc-image-builder
        vars:
          IMAGE: '{{.TAG}}'

  build:
    requires:
      vars: [FILE, TAG, ARCH, FEDORA_MAJOR_VERSION]
    cmd: >
      podman build
      --platform linux/{{.ARCH}}
      --build-arg FEDORA_MAJOR_VERSION={{.FEDORA_MAJOR_VERSION}}
      --build-arg BASE_REPO=localhost
      -f {{.FILE}}
      -t {{.TAG}}
      .

  bootc-image-builder:
    requires:
      vars: [IMAGE, BOOTC_IMAGE_TYPE, ARCH]
    cmd: >
      podman run --rm -it --privileged
      --security-opt label=type:unconfined_t
      -v $(pwd)/bootc-config.toml:/config.toml:ro
      -v $(pwd)/output:/output
      -v /var/lib/containers/storage:/var/lib/containers/storage
      --platform linux/{{.ARCH}}
      quay.io/centos-bootc/bootc-image-builder:latest
      --target-arch {{.ARCH}}
      --rootfs xfs
      --type {{.BOOTC_IMAGE_TYPE}}
      --local {{.IMAGE}}

  boot-qcow2-aarch64:
    cmd: >
      qemu-system-aarch64
      -machine virt
      -monitor stdio
      -accel hvf
      -smp 4
      -bios /opt/homebrew/Cellar/qemu/9.1.2/share/qemu/edk2-aarch64-code.fd
      -m 1G
      -display default,show-cursor=on
      -cpu host
      -device qemu-xhci
      -device usb-kbd
      -device usb-tablet
      -device intel-hda
      -device hda-duplex
      -device virtio-gpu-pci
      -drive file=./output/image/disk.raw,format=raw,if=virtio
