---
version: 3

dotenv: [.env]

includes:
  qemu: .taskfiles/qemu
  containers: .taskfiles/containers
  images: .taskfiles/images
  k8s-node: containers/k8s-node

vars:
  FEDORA_MAJOR_VERSION: latest
  ARCH: { sh: uname -m }
  BOOTC_IMAGE_TYPE: raw
  BASE_REPO: ghcr.io/kevindurb

tasks:
  default: task --list-all
