---
version: 3

dotenv: [.env]

includes:
  qemu: .taskfiles/qemu
  containers: .taskfiles/containers
  bootc: .taskfiles/bootc

vars:
  FEDORA_MAJOR_VERSION: latest
  ARCH: amd64
  BOOTC_IMAGE_TYPE: raw

tasks:
  steamdeck:
    deps: []
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/steamdeck/Containerfile
        TAG: localhost/steamdeck

  tablet:
    deps: []
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/tablet/Containerfile
        TAG: localhost/tablet

  tablet-bootc:
    deps: [gnome-bootc]
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/tablet-bootc/Containerfile
        TAG: localhost/tablet-bootc

  workstation:
    deps: []
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/workstation/Containerfile
        TAG: localhost/workstation

  workstation-bootc:
    deps: [kde-bootc]
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/workstation-bootc/Containerfile
        TAG: localhost/workstation-bootc

  kde-bootc:
    deps: [base-graphical-bootc]
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/kde-bootc/Containerfile
        TAG: localhost/kde-bootc

  gnome-bootc:
    deps: [base-graphical-bootc]
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/gnome-bootc/Containerfile
        TAG: localhost/gnome-bootc

  base-graphical-bootc:
    deps: []
    cmd:
      task: containers:build
      vars:
        FILE: ./containers/base-graphical-bootc/Containerfile
        TAG: localhost/base-graphical-bootc
