---
version: 3

dotenv: [.env]

includes:
  qemu: .taskfiles/qemu
  containers: .taskfiles/containers
  images: .taskfiles/images

vars:
  ARCH: { sh: uname -m }
  BOOTC_IMAGE_TYPE: raw
  BASE_REPO: ghcr.io/kevindurb

tasks:
  default: task --list-all

  lint:
    desc: Lint all Containerfiles with hadolint
    sources:
      - containers/*/Containerfile
    cmds:
      - for: sources
        task: lint:file
        vars:
          FILE: '{{.ITEM}}'

  lint:file:
    desc: Lint a specific Containerfile
    requires:
      vars: [FILE]
    vars:
      FILE: '{{.FILE}}'
    cmds:
      - |
        echo "Linting {{.FILE}}"
        podman run --rm -i \
          -v "$(pwd)/.hadolint.yaml:/.config/hadolint.yaml:ro" \
          ghcr.io/hadolint/hadolint \
          < {{.FILE}}

  hooks:pre-commit:
    desc: Run pre-commit checks
    cmd:
      task: lint

  hooks:install:
    desc: Install git hooks
    cmds:
      - mkdir -p .git/hooks
      - |
        cat > .git/hooks/pre-commit << 'EOF'
        #!/usr/bin/env bash
        set -euo pipefail
        task hooks:pre-commit
        EOF
      - chmod +x .git/hooks/pre-commit
      - echo "Git hooks installed"
