---
version: 3

vars:
  FEDORA_MAJOR_VERSION: 41
  ARCH: amd64

tasks:
  full-build:
    requires:
      vars: [NAME]
    cmds:
      - task: build
        vars:
          NAME: '{{.NAME}}'
          TAG: '{{.NAME}}-bootc'
      - task: build-qcow2
        vars:
          IMAGE: 'localhost/{{.NAME}}-bootc'

  build:
    requires:
      vars: [NAME, TAG]
    cmd: >
      podman build
      --platform linux/{{.ARCH}}
      --build-arg FEDORA_MAJOR_VERSION={{.FEDORA_MAJOR_VERSION}}
      -f ./containers/{{.NAME}}/Containerfile
      -t {{.TAG}}
      .

  bootc-image-builder:
    requires:
      vars: [IMAGE, TYPE]
    cmd: >
      podman run --rm -it --privileged
      --security-opt label=type:unconfined_t
      -v $(pwd)/bootc-config.toml:/config.toml:ro
      -v $(pwd)/output:/output
      -v /var/lib/containers/storage:/var/lib/containers/storage
      --platform linux/{{.ARCH}}
      quay.io/centos-bootc/bootc-image-builder:latest
      --target-arch {{.ARCH}}
      --rootfs xfs
      --type {{.TYPE}}
      --local {{.IMAGE}}

  build-qcow2:
    requires:
      vars: [IMAGE]
    cmd:
      task: bootc-image-builder
      vars:
        TYPE: qcow2
        IMAGE: '{{.IMAGE}}'

  build-iso:
    requires:
      vars: [IMAGE]
    cmd:
      task: bootc-image-builder
      vars:
        TYPE: anaconda-iso
        IMAGE: '{{.IMAGE}}'
