ARG FEDORA_MAJOR_VERSION=rawhide
ARG BASE_REPO=ghcr.io/kevindurb
FROM ${BASE_REPO}/base-graphical-bootc:${FEDORA_MAJOR_VERSION}

RUN dnf group install -y gnome-desktop && \
  dnf install -y \
  pinentry-gnome3 \
  desktop-backgrounds-gnome \
  qadwaitadecorations-qt5 \
  evince-thumbnailer \
  evince-previewer \
  totem-video-thumbnailer \
  gnome-software-rpm-ostree && \
  dnf clean all && \
  systemctl enable gdm
