ARG FEDORA_MAJOR_VERSION=rawhide
ARG BASE_REPO=ghcr.io/kevindurb
FROM ${BASE_REPO}/base-graphical-bootc:${FEDORA_MAJOR_VERSION}

RUN dnf group install -y \
  gnome-desktop && \
  dnf clean all && \
  systemctl enable gdm

RUN bootc container lint