FROM ghcr.io/ublue-os/ucore-minimal:stable@sha256:5c4dbdddc062cb0ced0f573f6c8f5e525715273591c31b9db42f12984e0d5b4d

ARG FILES_ROOT=./containers/wg-hub/files

RUN dnf install -y \
  nebula \
  node-exporter \
  wireguard-tools \
  && dnf clean all

COPY ${FILES_ROOT}/modules.conf /etc/modules-load.d/99-wg.conf
COPY ${FILES_ROOT}/sysctl.conf /etc/sysctl.d/99-wg.conf

RUN bootc container lint
