FROM ghcr.io/ublue-os/ucore-minimal:stable@sha256:a17e80a1e968190514be28e25acec72a54f61a4fc3078337d8ea4d78915930cd

ARG FILES_ROOT=./containers/wg-hub/files

RUN dnf install -y \
  nebula \
  node-exporter \
  wireguard-tools \
  && dnf clean all

COPY ${FILES_ROOT}/modules.conf /etc/modules-load.d/99-wg.conf
COPY ${FILES_ROOT}/sysctl.conf /etc/sysctl.d/99-wg.conf

RUN bootc container lint
