FROM ghcr.io/ublue-os/ucore-minimal:stable@sha256:77ce9e9c3ce330469645d4faa4d80ceea3ec4d7d832025d8fc045587ea18665b

ARG FILES_ROOT=./containers/wg-hub/files

RUN dnf install -y \
  nebula \
  node-exporter \
  wireguard-tools \
  && dnf clean all

COPY ${FILES_ROOT}/modules.conf /etc/modules-load.d/99-wg.conf
COPY ${FILES_ROOT}/sysctl.conf /etc/sysctl.d/99-wg.conf

RUN bootc container lint
