ARG FEDORA_MAJOR_VERSION
ARG BASE_REPO=ghcr.io/kevindurb
FROM ${BASE_REPO}/base-graphical-bootc:${FEDORA_MAJOR_VERSION}

RUN dnf group install -y kde-desktop && \
  dnf clean all && \
  systemctl enable sddm

RUN bootc container lint
