FROM docker.io/library/golang:1.25@sha256:a22b2e6c5e753345b9759fba9e5c1731ebe28af506745e98f406cc85d50c828e AS build
WORKDIR /app
# renovate: datasource=github-tags depName=apx packageName=vanilla-os/apx
ARG APX_VERSION=v2.4.5
RUN GOBIN=/app go install github.com/vanilla-os/apx@${APX_VERSION}

FROM scratch
WORKDIR /
COPY --from=build /app/apx .
