FROM docker.io/library/golang:1.25@sha256:f60eaa87c79e604967c84d18fd3b151b3ee3f033bcdade4f3494e38411e60963 AS build
WORKDIR /app
# renovate: datasource=github-tags depName=apx packageName=vanilla-os/apx
ARG APX_VERSION=v2.4.5
RUN GOBIN=/app go install github.com/vanilla-os/apx@${APX_VERSION}

FROM scratch
WORKDIR /
COPY --from=build /app/apx .
