FROM docker.io/library/golang:1.25@sha256:8bbd14091f2c61916134fa6aeb8f76b18693fcb29a39ec6d8be9242c0a7e9260 AS build
WORKDIR /app
# renovate: datasource=github-tags depName=apx packageName=vanilla-os/apx
ARG APX_VERSION=v2.5.0
RUN GOBIN=/app go install github.com/vanilla-os/apx@${APX_VERSION}

FROM scratch
WORKDIR /
COPY --from=build /app/apx .
