ARG FEDORA_MAJOR_VERSION=rawhide
FROM quay.io/fedora/fedora-bootc:${FEDORA_MAJOR_VERSION}
ARG TARGETARCH

COPY ./containers/lima-bootc/files/lima-guestagent-${TARGETARCH} /usr/bin/lima-guestagent
COPY ./containers/lima-bootc/files/lima-guestagent.service /etc/systemd/system/

RUN dnf install -y \
  openssh-server \
  cloud-init \
  sshfs \
  dnf5-plugins && \
  dnf clean all && \
  systemctl enable sshd && \
  systemctl enable lima-guestagent && \
  ln -s /var /Users

COPY ./packages/dev.packages /tmp
RUN dnf5 copr enable -y atim/lazygit && \
  dnf5 copr enable -y atim/starship && \
  dnf5 install -y $(cat /tmp/dev.packages) && \
  dnf5 clean all

RUN bootc container lint
