FROM quay.io/fedora/fedora-bootc:44@sha256:c7fd46089e579da477af432a532b559723adff00ac0585ed3f6868716604dac9

ADD ./containers/devpi/files/wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

RUN bootc container lint
