ARG FEDORA_MAJOR_VERSION
FROM quay.io/fedora/fedora-bootc:${FEDORA_MAJOR_VERSION}

ADD ./containers/devpi/files/wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh
