FROM quay.io/fedora/fedora-bootc:42

ADD ./containers/devpi/files/wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

RUN bootc container lint
