---
version: 3

tasks:
  bootc-image-builder:
    requires:
      vars: [IMAGE, BOOTC_IMAGE_TYPE, ARCH]
    cmd: >
      podman run --rm -it --privileged
      --security-opt label=type:unconfined_t
      -v $(pwd)/bootc-config.toml:/config.toml:ro
      -v $(pwd)/dist:/output
      -v /var/lib/containers/storage:/var/lib/containers/storage
      --platform linux/{{.ARCH}}
      quay.io/centos-bootc/bootc-image-builder:latest
      --target-arch {{.ARCH}}
      --rootfs xfs
      --type {{.BOOTC_IMAGE_TYPE}}
      --local {{.IMAGE}}

  bootc-install-to-raw:
    requires:
      vars: [IMAGE, ARCH]
    cmds:
      - cmd: rm -rf ./dist/disk.raw
      - cmd: truncate -s 20G ./dist/disk.raw
      - cmd: >
          podman run --rm -it --privileged
          --security-opt label=type:unconfined_t
          -v /var/lib/containers:/var/lib/containers
          -v /dev:/dev
          -v ./dist/disk.raw:/disk.raw
          --pid=host
          --platform linux/{{.ARCH}}
          {{.IMAGE}}
          bootc install to-disk
          --target-transport containers-storage
          --generic-image
          --filesystem xfs
          --via-loopback /disk.raw
