---
version: 3

tasks:
  bootc-image-builder:
    requires:
      vars: [IMAGE, BOOTC_IMAGE_TYPE, ARCH]
    cmd: >
      podman run --rm -it --privileged
      --security-opt label=type:unconfined_t
      -v $(pwd)/bootc-config.toml:/config.toml:ro
      -v $(pwd)/output:/output
      -v /var/lib/containers/storage:/var/lib/containers/storage
      --platform linux/{{.ARCH}}
      quay.io/centos-bootc/bootc-image-builder:latest
      --target-arch {{.ARCH}}
      --rootfs xfs
      --type {{.BOOTC_IMAGE_TYPE}}
      --local {{.IMAGE}}
