FROM ghcr.io/ublue-os/ucore-minimal:stable-nvidia@sha256:abf13571a2ab91e30eac44c57f3b96f2a186bc63e2e1019d6c0c619d45b84a49

ARG K3S_SELINUX_VERSION=1.6-1
RUN dnf install -y https://rpm.rancher.io/k3s/latest/common/centos/9/noarch/k3s-selinux-${K3S_SELINUX_VERSION}.el9.noarch.rpm && \
  dnf clean all

ARG FILES_ROOT=./containers/k8s-node/files
ARG K3S_VERSION=v1.34.1+k3s1

ADD ${FILES_ROOT}/modules.conf /etc/modules-load.d/k8s.conf
ADD ${FILES_ROOT}/sysctl.conf /etc/sysctl.d/k8s.conf
ADD ${FILES_ROOT}/k3s-${K3S_VERSION} /usr/local/bin/k3s
ADD ${FILES_ROOT}/k3s.service /etc/systemd/system/
ADD ${FILES_ROOT}/k3s-agent.service /etc/systemd/system/

RUN dnf remove -y \
  zram-generator-defaults

RUN systemctl disable firewalld \
    && systemctl enable tailscaled
