# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

vars:
  HOSTS:
    - kube-master-01
    - kube-master-02
    - kube-master-03
    - kube-storage-01
    - kube-storage-02
    - kube-storage-03
    - kube-big-01

tasks:
  build:
    desc: Build the bootc container image for K8s nodes
    cmd: >
      podman build
      -t ghcr.io/kevindurb/k8s-node:latest
      -f ./bootc/node.Containerfile
      ./bootc

  genignition:
    desc: Generate ignition files for all hosts in hosts.yml
    cmds:
      - for: { var: HOSTS }
        cmd: |
          minijinja-cli \
            --select "{{.ITEM}}" \
            ./node.bu.j2 \
            ./hosts.yml | \
          butane \
            --strict \
            --pretty \
            -o ./ignition/{{.ITEM}}.ign \
            --

  download-iso:
    cmd: >
      podman run --rm -v ../dist:/data
      quay.io/coreos/coreos-installer:release
      download -s stable -p metal -f iso -a x86_64 -C /data

  build-isos:
    deps: [download-iso]
    vars:
      ISO_FILENAME:
        sh: ls ../dist/fedora-coreos-*.iso | tail -1 | xargs basename
    cmds:
      - for: { var: HOSTS }
        cmd: rm -f ../dist/{{.ITEM}}.iso
      - for: { var: HOSTS }
        cmd: >
          podman run --rm -it --privileged
          -v ./ignition/{{.ITEM}}.ign:/config.ign:ro
          -v ../dist:/data
          quay.io/coreos/coreos-installer:release
          iso customize
          --dest-device /dev/sda
          --dest-ignition /config.ign
          --output /data/{{.ITEM}}.iso
          /data/{{.ISO_FILENAME}}
