FROM ghcr.io/ublue-os/ucore-minimal:stable@sha256:a92f4237a5f595a2e95355f04052409d024401c3c63be364dcd3ee9c1ae129a9

ARG FILES_ROOT=./containers/router/files

RUN dnf install -y \
  node-exporter \
  dnsmasq \
  && dnf clean all

COPY ${FILES_ROOT}/dnsmasq.conf /etc/dnsmasq.d/99-router.conf
COPY ${FILES_ROOT}/sysctl.conf /etc/sysctl.d/99-router.conf
COPY ${FILES_ROOT}/nftables.conf /etc/nftables.conf

RUN systemctl enable nftables \
  && systemctl unmask dnsmasq.service \
  && systemctl unmask dnsmasq.socket \
  && systemctl enable dnsmasq \
  && systemctl disable systemd-resolved

RUN bootc container lint
