FROM quay.io/fedora/fedora-bootc:44@sha256:c7fd46089e579da477af432a532b559723adff00ac0585ed3f6868716604dac9

RUN dnf install -y \
  dnsmasq

COPY ./containers/router/router.conf /etc/dnsmasq.d/

RUN bootc container lint
