FROM ghcr.io/ublue-os/ucore-minimal:stable@sha256:c401b2a00a8f7fa7861c7484c475192b0a492f1c4de01dda3ac9c4f4bbf274cd

ARG FILES_ROOT=./containers/router/files

RUN dnf install -y \
  node-exporter \
  dnsmasq \
  && dnf clean all

COPY ${FILES_ROOT}/dnsmasq.conf /etc/dnsmasq.d/99-router.conf
COPY ${FILES_ROOT}/sysctl.conf /etc/sysctl.d/99-router.conf
COPY ${FILES_ROOT}/nftables.conf /etc/nftables.conf

RUN systemctl enable nftables \
  && systemctl unmask dnsmasq.service \
  && systemctl unmask dnsmasq.socket \
  && systemctl enable dnsmasq \
  && systemctl disable systemd-resolved

RUN bootc container lint
