ARG FEDORA_MAJOR_VERSION=rawhide
FROM quay.io/fedora/fedora-bootc:${FEDORA_MAJOR_VERSION}

COPY ./packages/codecs.packages /tmp
RUN dnf install -y $(cat /tmp/packages/codecs.packages) && \
  dnf clean all

# https://pagure.io/workstation-ostree-config/blob/main/f/common.yaml
# https://pagure.io/workstation-ostree-config/blob/main/f/common-packages.yaml

COPY ./containers/base-graphical-bootc/base-graphical-bootc.groups /tmp
COPY ./containers/base-graphical-bootc/base-graphical-bootc.packages /tmp
RUN dnf group install -y $(cat /tmp/base-graphical-bootc.groups) && \
  dnf install -y $(cat /tmp/base-graphical-bootc.packages) && \
  dnf clean all && \
  systemctl set-default graphical.target

# Add missing /var/run symlink
RUN rm /var/run -rf && ln -s /run /var/

RUN bootc container lint
