ARG FEDORA_MAJOR_VERSION
ARG BASE_REPO=ghcr.io/kevindurb
FROM ${BASE_REPO}/gnome-bootc:${FEDORA_MAJOR_VERSION}

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

ADD https://pkg.surfacelinux.com/fedora/linux-surface.repo /etc/yum.repos.d/

RUN dnf install -y --allowerasing \
  iptsd \
  libwacom-surface \
  gnome-shell-extension-gsconnect \
  gnome-shell-extension-caffeine \
  gnome-shell-extension-appindicator && \
  dnf clean all

RUN bootc container lint
