ARG FEDORA_MAJOR_VERSION
FROM quay.io/fedora/fedora-kinoite:${FEDORA_MAJOR_VERSION}

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

ARG FEDORA_MAJOR_VERSION
COPY ./containers/mithril/files/steam.packages /tmp
RUN dnf install -y \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-${FEDORA_MAJOR_VERSION}.noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${FEDORA_MAJOR_VERSION}.noarch.rpm && \
  dnf install -y $(cat /tmp/steam.packages) && \
  dnf clean all

COPY ./containers/mithril/files/gamescope-session /usr/bin
COPY ./containers/mithril/files/steamos-session-select /usr/bin
COPY ./containers/mithril/files/gamescope-session.desktop /usr/share/wayland-sessions
COPY ./containers/mithril/files/steamos.conf /etc/sddm.conf.d
