# TODO: switch to upstream when available
FROM ghcr.io/ublue-os/silverblue-bootc:40

ENV FLATPAK_RUNTIME=org.freedesktop.Platform//1.14
ENV FLATPAK_SYSTEM_DIR=/var/lib/flatpak

COPY files/flathub.flatpakrepo /etc/flatpak/repo/flathub.flatpakrepo

RUN flatpak install --system --noninteractive --assumeyes flathub com.brave.Browser
