FROM ghcr.io/ublue-os/bazzite-deck:stable

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh && \
  dnf5 install --assumeyes dnf5-plugins && \
  dnf5 install --assumeyes snapd && \
  dnf5 clean all && \
  systemctl enable snapd.service && \
  /usr/bin/ln -sf /var/lib/snapd/snap /

RUN bootc container lint
