ARG FEDORA_MAJOR_VERSION
FROM ghcr.io/ublue-os/bazzite-deck:${FEDORA_MAJOR_VERSION}

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

RUN dnf install -y \
  dnf5-plugins \
  dialog \
  edk2-ovmf \
  edk2-tools \
  genisoimage \
  krdp \
  libvirt \
  mesa-demos \
  nmap-ncat \
  qemu \
  qemu-ui-sdl \
  spice-gtk-tools \
  swtpm \
  virt-manager && \
  dnf clean all

RUN bootc container lint
