FROM ghcr.io/ublue-os/bazzite-deck:stable@sha256:d6d38c099793008237859718afacb56337b8b461d3907400e1c0e749558213a8

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

RUN bootc container lint
