---
version: 3

tasks:
  build:
    internal: true
    requires:
      vars: [FILE, TAG, ARCH, BASE_REPO]
    cmd: >
      podman build
      --platform linux/{{.ARCH}}
      -f {{.FILE}}
      -t {{.BASE_REPO}}/{{.TAG}}
      .

  build:*:
    vars:
      CONTAINER: '{{index .MATCH 0}}'
    cmd:
      task: build
      vars:
        FILE: ./containers/{{.CONTAINER}}/Containerfile
        TAG: '{{.CONTAINER}}'
