ARG FEDORA_MAJOR_VERSION
FROM ghcr.io/ublue-os/aurora:${FEDORA_MAJOR_VERSION}

COPY --from=ghcr.io/kevindurb/apx:latest /apx /usr/bin/

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh
