ARG FEDORA_MAJOR_VERSION=rawhide
FROM ghcr.io/kevindurb/kde-bootc:${FEDORA_MAJOR_VERSION}

RUN mkdir /tmp/scripts

COPY ./scripts/rpm-fusion.sh /tmp/scripts
RUN /tmp/scripts/rpm-fusion.sh

COPY ./scripts/snapd-install.sh /tmp/scripts
RUN /tmp/scripts/snapd-install.sh

COPY ./scripts/tailscale-install.sh /tmp/scripts
RUN /tmp/scripts/tailscale-install.sh

COPY ./scripts/codecs-install.sh /tmp/scripts
RUN /tmp/scripts/codecs-install.sh

COPY ./scripts/base-packages-install.sh /tmp/scripts
RUN /tmp/scripts/base-packages-install.sh

COPY ./scripts/chezmoi-install.sh /tmp/scripts
RUN /tmp/scripts/chezmoi-install.sh

COPY ./scripts/syncthing-install.sh /tmp/scripts
RUN /tmp/scripts/syncthing-install.sh

COPY ./scripts/steam-setup.sh /tmp/scripts
RUN /tmp/scripts/steam-setup.sh

COPY ./scripts/openrgb-udev-rules.sh /tmp/scripts
RUN /tmp/scripts/openrgb-udev-rules.sh

COPY ./scripts/dev-packages-install.sh /tmp/scripts
RUN /tmp/scripts/dev-packages-install.sh
