ARG FEDORA_MAJOR_VERSION=rawhide
FROM quay.io/fedora/fedora-bootc:${FEDORA_MAJOR_VERSION}

RUN dnf install -y dnf5-plugins && \
  dnf group install -y \
  base-graphical \
  container-management \
  fonts \
  hardware-support \
  multimedia \
  networkmanager-submodules \
  printing && \
  dnf clean all && \
  systemctl set-default graphical.target 
