# TODO: switch to bootc when available
FROM ghcr.io/ublue-os/bazzite-gnome-nvidia:40

RUN mkdir /tmp/scripts

COPY ./scripts/snapd-install.sh /tmp/scripts
RUN /tmp/scripts/snapd-install.sh

COPY ./scripts/tailscale-install.sh /tmp/scripts
RUN /tmp/scripts/tailscale-install.sh

COPY ./scripts/codecs-install.sh /tmp/scripts
RUN /tmp/scripts/codecs-install.sh

COPY ./scripts/base-packages-install.sh /tmp/scripts
RUN /tmp/scripts/base-packages-install.sh

COPY ./scripts/gnome-extensions-install.sh /tmp/scripts
RUN /tmp/scripts/gnome-extensions-install.sh

COPY ./scripts/syncthing-install.sh /tmp/scripts
RUN /tmp/scripts/syncthing-install.sh

