FROM ghcr.io/ublue-os/kinoite-main:43@sha256:c66424345f89d5c5d54aafa9241271716f1ef6aced6b36595b41926767e5542c

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

COPY ./scripts/uninstall-firefox.sh /tmp
RUN /tmp/uninstall-firefox.sh

RUN bootc container lint
