FROM ghcr.io/ublue-os/kinoite-main:43@sha256:e275bfd9f5efbb68a935dfa509a0f54f522acb4c67898a1801daadb10fc79536

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

COPY ./scripts/uninstall-firefox.sh /tmp
RUN /tmp/uninstall-firefox.sh

RUN bootc container lint
