ARG FEDORA_MAJOR_VERSION=rawhide
FROM ghcr.io/kevindurb/gnome-bootc:${FEDORA_MAJOR_VERSION}

RUN sudo dnf config-manager \
  addrepo --from-repofile=https://pkg.surfacelinux.com/fedora/linux-surface.repo

RUN dnf install -y --allowerasing \
  kernel-surface \
  iptsd \
  libwacom-surface \
  surface-secureboot

RUN dnf install -y snapd && \
  systemctl enable snapd.service && \
  /usr/bin/ln -sf /var/lib/snapd/snap /

RUN dnf install -y tailscale && \
  systemctl enable tailscaled.service

RUN dnf install -y \
  gstreamer1-plugin-libav \
  gstreamer1-plugin-openh264 \
  gstreamer1-plugins-base \
  gstreamer1-plugins-good \
  heif-pixbuf-loader

RUN dnf install -y \
  gnome-shell-extension-gsconnect \
  gnome-shell-extension-caffeine \
  gnome-shell-extension-appindicator

RUN sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/bin

RUN dnf install -y syncthing && \
  systemctl --global enable syncthing.service

COPY ./scripts/dev-packages-install.sh /tmp
RUN /tmp/dev-packages-install.sh
