FROM ghcr.io/kevindurb/kinoite:latest

RUN dnf5 install -y \
  fprintd \
  libcamera \
  libcamera-tools \
  libcamera-gstreamer \
  libcamera-ipa \
  pipewire-plugin-libcamera && \
  dnf5 clean all

RUN bootc container lint
