FROM quay.io/fedora-ostree-desktops/cosmic-atomic:44

COPY --from=ghcr.io/kevindurb/dev-scripts:latest / /tmp

RUN /tmp/install-dev-base.sh
RUN /tmp/uninstall-firefox.sh

RUN dnf install --assumeyes \
  waydroid \
  && dnf clean all

COPY overlay/ /

RUN bootc container lint
