ARG FEDORA_MAJOR_VERSION
ARG BASE_REPO=ghcr.io/kevindurb
FROM ${BASE_REPO}/kde-bootc:${FEDORA_MAJOR_VERSION}

RUN dnf install -y snapd && \
  systemctl enable snapd.service && \
  /usr/bin/ln -sf /var/lib/snapd/snap /

RUN dnf install -y tailscale && \
  systemctl enable tailscaled.service

RUN dnf install -y syncthing && \
  systemctl --global enable syncthing.service

ADD https://openrgb.org/releases/release_0.9/60-openrgb.rules /usr/lib/udev/rules.d/

COPY ./packages/dev.packages /tmp
RUN dnf5 copr enable -y atim/lazygit && \
  dnf5 copr enable -y atim/starship && \
  dnf5 install -y $(cat /tmp/dev.packages) && \
  dnf5 clean all

RUN bootc container lint
