ARG FEDORA_MAJOR_VERSION
ARG BASE_REPO=ghcr.io/kevindurb
FROM ${BASE_REPO}/kde-bootc:${FEDORA_MAJOR_VERSION}

COPY ./scripts/install-dev-base.sh /tmp
RUN /tmp/install-dev-base.sh

ADD https://openrgb.org/releases/release_0.9/60-openrgb.rules /usr/lib/udev/rules.d/

RUN bootc container lint
