---
name: build-disk-images
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of image to build disk images from
        type: string
        default: latest
  workflow_call:
    inputs:
      tag:
        description: Tag of image to build disk images from
        type: string
        default: latest

env:
  ARCH: amd64
  IMAGE_REPO: ghcr.io/kevindurb

jobs:
  build-disk-images:
    name: Build Disk Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        recipe:
          # TODO: add back when these support bootc
          # - steamdeck-bootc
          # - htpc-bootc
          - tablet-bootc
          - router-bootc
          - workstation-bootc
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Setup Image Builder Config
        run: echo "$IMAGE_BUILDER_CONFIG" > ./config.toml
        env:
          IMAGE_BUILDER_CONFIG: ${{ secrets.IMAGE_BUILDER_CONFIG }}

      - name: Build qcow image
        run: |
          docker run --rm \
          --privileged \
          --security-opt label=type:unconfined_t \
          -v $(pwd)/config.toml:/config.toml:ro \
          -v $(pwd)/output:/output \
          quay.io/centos-bootc/bootc-image-builder:latest \
          --type qcow2 \
          --rootfs xfs \
          --output /output \
          --target-arch ${{ env.ARCH }} \
          ${{ env.IMAGE_REPO }}/${{ matrix.recipe }}:${{ inputs.tag }}

      - name: Upload image as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.recipe }}.qcow2
          path: |
            ./output/qcow2/disk.qcow2
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
