---
name: Create Release
on:
  push:
    tags: ['*']

jobs:
  build:
    name: Trigger image Build
    uses: kevindurb/bootc/.github/workflows/build.yml@main
    secrets: inherit

  build-isos:
    name: Trigger iso build
    uses: kevindurb/bootc/.github/workflows/build-isos.yml@main
    needs: [build]
    secrets: inherit

  build-disk-images:
    name: Trigger disk image build
    uses: kevindurb/bootc/.github/workflows/build-disk-images.yml@main
    needs: [build]
    secrets: inherit

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, build-disk-images, build-isos]
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: '*.iso,*.qcow'
