---
name: Create Release
on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    name: Trigger image Build
    uses: kevindurb/bootc/.github/workflows/build.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write

  build-isos:
    name: Trigger iso build
    uses: kevindurb/bootc/.github/workflows/build-isos.yml@main
    needs: [build]
    secrets: inherit

  build-disk-images:
    name: Trigger disk image build
    uses: kevindurb/bootc/.github/workflows/build-disk-images.yml@main
    needs: [build]
    secrets: inherit

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, build-disk-images, build-isos]
    permissions:
      contents: write
    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7

      - name: Download ISOs
        uses: actions/download-artifact@v4
        with:
          pattern: '*.iso'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.iso
