---
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '05 10 * * 1'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Self-hosted Renovate
        uses: renovatebot/github-action
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
